### PR TITLE
i2ceeprom - use mbed_official fork

### PR DESCRIPTION
**Pull request by 0xc0170**
To be able to fix/develop this fork.

Tested with k64f (using latest mbed-os master):

```
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target       | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR 10  Bytes     | 1      | 0      | OK     | 0.07               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR 100 Bytes     | 1      | 0      | OK     | 0.08               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR 2 Bytes       | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR Single Byte   | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 10  Bytes         | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 100 Bytes         | 1      | 0      | OK     | 0.08               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 2 Bytes           | 1      | 0      | OK     | 0.05               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR Single Byte       | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  Instantiation of I2C Object | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  LM75B Temperature Read      | 1      | 0      | OK     | 0.06               |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
```

As the current one is not anymore in the development (PR ignored for some time).

cc @BlackstoneEngineering

### CODE REVIEW

**Comment by 0xc0170** [comment]
cc @LMESTM

**Comment by LMESTM** [comment]
@0xc0170 thanks 
I'd like to test it but I'm not so good at hg usage, so if I cherry-pick this git commit , 
what are the next hg commands that I should use to get the up-to-date I2C library  ?

**Comment by 0xc0170** [comment]
just fetch my branch or use this lib (the link updated). do ``mbed update`` and it should fetch that i2c library to test.. Please read my comment about your pull request. I did not get full details how it fixes a problem (what problem it has).

**Comment by LMESTM** [comment]
@0xc0170 thanks - so let's mbed update :-) 
I actually answered your comment about the pull request yesterday

**Comment by 0xc0170** [comment]
>  I actually answered your comment about the pull request yesterday

Thanks, accepted. This PR should get an update then use the latest version (I'll retest it again).

This should be the new version: https://developer.mbed.org/users/mbed_official/code/I2CEeprom/rev/973c4289c44c

**Comment by 0xc0170** [comment]
Done, rebased. It now includes the latest version.

Retested, mbed-os latest master, k64f, GCC_ARM:

```
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target       | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR 10  Bytes     | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR 100 Bytes     | 1      | 0      | OK     | 0.08               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR 2 Bytes       | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm 2nd WR Single Byte   | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 10  Bytes         | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 100 Bytes         | 1      | 0      | OK     | 0.08               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 2 Bytes           | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR Single Byte       | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  Instantiation of I2C Object | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  LM75B Temperature Read      | 1      | 0      | OK     | 0.06               |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
```

@LMESTM Please retest !

**Comment by LMESTM** [comment]
@0xc0170  Works ok here.  
Although I don't see where your "2nd WR" tests come from.

+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| NUCLEO_L476RG-ARM | NUCLEO_L476RG | tests-api-i2c | I2C -  EEProm WR 10  Bytes         | 1      | 0      | OK     | 0.33               |
| NUCLEO_L476RG-ARM | NUCLEO_L476RG | tests-api-i2c | I2C -  EEProm WR 100 Bytes         | 1      | 0      | OK     | 0.72               |
| NUCLEO_L476RG-ARM | NUCLEO_L476RG | tests-api-i2c | I2C -  EEProm WR 2 Bytes           | 1      | 0      | OK     | 0.29               |
| NUCLEO_L476RG-ARM | NUCLEO_L476RG | tests-api-i2c | I2C -  EEProm WR Single Byte       | 1      | 0      | OK     | 0.17               |
| NUCLEO_L476RG-ARM | NUCLEO_L476RG | tests-api-i2c | I2C -  Instantiation of I2C Object | 1      | 0      | OK     | 0.06               |
| NUCLEO_L476RG-ARM | NUCLEO_L476RG | tests-api-i2c | I2C -  LM75B Temperature Read      | 1      | 0      | OK     | 0.13               |
+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+

+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| NUCLEO_F401RE-ARM | NUCLEO_F401RE | tests-api-i2c | I2C -  EEProm WR 10  Bytes         | 1      | 0      | OK     | 0.33               |
| NUCLEO_F401RE-ARM | NUCLEO_F401RE | tests-api-i2c | I2C -  EEProm WR 100 Bytes         | 1      | 0      | OK     | 0.72               |
| NUCLEO_F401RE-ARM | NUCLEO_F401RE | tests-api-i2c | I2C -  EEProm WR 2 Bytes           | 1      | 0      | OK     | 0.29               |
| NUCLEO_F401RE-ARM | NUCLEO_F401RE | tests-api-i2c | I2C -  EEProm WR Single Byte       | 1      | 0      | OK     | 0.18               |
| NUCLEO_F401RE-ARM | NUCLEO_F401RE | tests-api-i2c | I2C -  Instantiation of I2C Object | 1      | 0      | OK     | 0.08               |
| NUCLEO_F401RE-ARM | NUCLEO_F401RE | tests-api-i2c | I2C -  LM75B Temperature Read      | 1      | 0      | OK     | 0.12               |
+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+

**Comment by 0xc0170** [comment]
@BlackstoneEngineering +1 ?

**Comment by BlackstoneEngineering** [comment]
@0xc0170 if I understand it correctly you forked the library, fixed the issue, and updated the latest master branch of CI Test shiled to use it correct? Assuming this works then I am perfectly happy with this!

**Comment by 0xc0170** [comment]
Tested with nuvoton also, all OK.

**Pull request merged**
