### PR TITLE
STM32 pin configuration update

### PR DESCRIPTION
**Pull request by jeromecoutant**
I have tested several STM32 devices with ci shield.
Here is the pin configuration update.
Thx

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
@jeromecoutant have you tested this with all the relevant boards and verified the CI Tests pass?

**Comment by 0xc0170** [comment]
> @jeromecoutant have you tested this with all the relevant boards and verified the CI Tests pass?

Please paste here the test results. We can reproduce this locally, and compare. Always appreciated to share how this was tested (prior the patch, after the patch).

**Comment by jeromecoutant** [comment]
Yes, this was tested

**Comment by 0xc0170** [comment]
> Yes, this was tested

Please paste some test results, even in hte commit message (new paragraph there could contain those). So anyone running those, could compare if any problem arises.

**Comment by jeromecoutant** [comment]
Hi
I don't save test logs...
But with this patch, tests-api-analogout and pwm are OK for all tested STM32 devices.

You can check also MBED boards page to check the pinout :
https://developer.mbed.org/platforms/?pvend=10

**Comment by 0xc0170** [comment]
> I don't save test logs...

Please do for future. always appreciated to have those for any PR (mbed-os or anywhere else).

>  But with this patch, tests-api-analogout and pwm are OK for all tested STM32 devices.

+1

**Comment by 0xc0170** [comment]
Thanks for the link, I verified few boards there, LGTM

**Pull request merged**
