### PR TITLE
Seperated TESTS/API/PWM into three seperate tests.

### PR DESCRIPTION
**Pull request by brandonboesch**
Instead of having only a single pwm test which measures interrupts on both rise and fall triggers, we now have it seperated as follows:

TESTS/API/PWM_rise - Tests with only rising triggers at a set period and set duty cycle

TESTS/API/PWM_fall - Tests with only falling triggers at a set period and set duty cycle

TESTS/API/PWM_rise_fall - Tests with both rising and falling triggers at multiple periods and duty cycles

### CODE REVIEW

**Comment by mray19027** [comment]
Adds the features requested here: #58

**Comment by brandonboesch** [comment]
@BlackstoneEngineering , the binary file has been removed.  Good catch!

**Comment by mray19027** [comment]
@khj098765 Awaiting feedback from you to see if this satisfies the requirement for the wiznet boards

**Comment by BlackstoneEngineering** [comment]
@andrewc-arm , can you please test this on wiznet hardware so we can proceed.

**Comment by khj098765** [comment]
@mray19027 @BlackstoneEngineering @andrewc-arm 
The test was completed successfully.
I attach the log file.
[test_pwm.txt](https://github.com/ARMmbed/ci-test-shield/files/1175098/test_pwm.txt)

**Pull request merged**
