### PR TITLE
AnalogIn test correction

### PR DESCRIPTION
**Pull request by bcostm**
Change initial value of prev_value + do only one adc read.

Correction of Issue https://github.com/ARMmbed/mbed-os/issues/2956

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
Wouldnt the simpler fix be just to initialize outputs and y to 1?

**Comment by pan-** [comment]
@BlackstoneEngineering I think the algorithm is done in the wrong order, it should be: 

* Read the current voltage
* Enable one more pin
* Assert that the voltage is now more important than the previous value read. 

it doesn't makes sense to assert that something is different if nothing has changed yet. 

```c++
    for(x = 0; x<5; x++) {
        prev_value = ain.read();
        y = (y<<1) + 1;
        outputs = y;
        TEST_ASSERT_MESSAGE(ain.read() > prev_value,"Analog Input did not incriment. Check that you have assigned valid pins in mbed_app.json file")
    }
```

**Comment by BlackstoneEngineering** [comment]
@pan- Agreed.
@bcostm does vincents solution work for you on your platform? Will merge Vincents solution on Friday if I do not hear back from you before then

**Comment by bcostm** [comment]
Hi,
Yes I agree. Let me check and I come back to you.

**Comment by BlackstoneEngineering** [comment]
I will close the issue and update directly to master, i've already got a couple patches pending, I'll toss in this one line change.

Thanks all for the input and helping us build a better ecosystem!

**Comment by 0xc0170** [comment]
@BlackstoneEngineering Whats the status of this PR?  Can it be closed?

**Comment by BlackstoneEngineering** [comment]
@0xc0170 yeah, the changes have been mainlined already

**Pull request closed without merging**
